### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by lisza** [propelml/propel#222]
```
in_alaska@xxxx propel (grid)⛺  ./tools/presubmit.js 
Delete dir ./build
node ./tools/cpplint.js
python ./deps/cpplint/cpplint.py binding.cc check.h
Done processing binding.cc
Done processing check.h
node ./tools/tslint.js
node ./node_modules/tslint/bin/tslint -p /Users/in_alaska/propel
node ./tools/stylelint.js
node ./node_modules/stylelint/bin/stylelint.js --config stylelint.json website/main.scss website/normalize.scss website/skeleton.scss website/syntax.scss website/syntax_dark.scss website/syntax_light.scss 
node ./tools/test.js
node ./tools/build_binding.js
mkdir /Users/in_alaska/propel/build
mkdir /Users/in_alaska/propel/build/Release
node tools/extract_so.js /Users/in_alaska/propel/build/Release
outDir /Users/in_alaska/propel/build/Release
Extracting /Users/in_alaska/propel/deps/libtensorflow/libtensorflow-cpu-darwin-x86_64.tar.gz
Extracting libtensorflow.so
/Users/in_alaska/propel/build/Release/libtensorflow.so
Extracting libtensorflow_framework.so
/Users/in_alaska/propel/build/Release/libtensorflow_framework.so
clang -c -o Release/binding.o ../binding.cc -I/usr/local/include/node -I/Users/in_alaska/propel/deps/libtensorflow/include -Wall -W -Wno-unused-parameter -std=gnu++0x -DNODE_GYP_MODULE_NAME=tensorflow-binding -DUSING_UV_SHARED=1 -DUSING_V8_SHARED=1 -DV8_DEPRECATION_WARNINGS=1 -D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64 
../binding.cc:703:50: error: use of undeclared identifier 'NAPI_AUTO_LENGTH'
  nstatus = napi_create_string_utf8(env, device, NAPI_AUTO_LENGTH, &js_device);
                                                 ^
../binding.cc:1006:7: error: use of undeclared identifier 'NAPI_AUTO_LENGTH'
      NAPI_AUTO_LENGTH,  // JavasScript class name length
      ^
../binding.cc:1019:7: error: use of undeclared identifier 'NAPI_AUTO_LENGTH'
      NAPI_AUTO_LENGTH,  // JavasScript class name length
      ^
../binding.cc:1123:33: error: cannot initialize a member subobject of type
      'napi_addon_register_func' (aka 'void (*)(napi_env__ *, napi_value__ *, napi_value__
      *, void *)') with an lvalue of type 'napi_value (napi_env, napi_value)' (aka
      'napi_value__ *(napi_env__ *, napi_value__ *)'): different number of parameters
      (4 vs 2)
NAPI_MODULE(tensorflow_binding, InitBinding)
                                ^~~~~~~~~~~
/usr/local/include/node/node_api.h:103:26: note: expanded from macro 'NAPI_MODULE'
  NAPI_MODULE_X(modname, regfunc, NULL, 0)
                         ^~~~~~~
/usr/local/include/node/node_api.h:92:7: note: expanded from macro 'NAPI_MODULE_X'
      regfunc,                                                        \
      ^~~~~~~
4 errors generated.
Error -c
Error ./tools/build_binding.js
Error ./tools/test.js
in_alaska@xxxx propel (grid)⛺  node -v
v8.4.0
```

**Comment by piscisaureus** [comment]
This is likely to be related to the node.js version you use. Does it still happen when you upgrade to node v8.9.x ?

**Comment by lisza** [comment]
Upgraded to the latest version (9.5.0) and those errors are gone. I get some others though:
```
node ./node_modules/ts-node/dist/bin.js --type-check test_browser.ts
2018-02-05 18:48:37.867485: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX
Using TF backend.
(node:80410) Warning: N-API is an experimental feature and could change at any time.
AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"
    at Console.assert (console.js:197:23)
    at Function.launch (/Users/in_alaska/propel/deps/node_modules/puppeteer/lib/Launcher.js:92:15)
    at <anonymous>
Error ./node_modules/ts-node/dist/bin.js
Error ./tools/test.js
```

The npm install (propel@3.0.0 install script) errors as well, which might be related to my Python version.

**Comment by ry** [comment]
That's expected. if you run `npm rebuild puppeteer` it'll be fixed.

can you paste the other error?

**Comment by lisza** [comment]
npm install errors:

```
in_alaska@xxxx propel (master)⛺  npm install

> propel@3.1.0 install /Users/in_alaska/propel
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Users/in_alaska/anaconda3/bin/python" is v3.6.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:264:7)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:363:11)
gyp ERR! stack     at Socket.emit (events.js:160:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:562:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/in_alaska/propel
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! propel@3.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the propel@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/in_alaska/.npm/_logs/2018-02-06T21_43_48_163Z-debug.log
```

**Comment by ry** [comment]
Your python is too new. This is a ugly cluster f of bad design - python3, gyp, node-gyp - which results in the error. This is why we don't use npm, node-gyp, nor gyp, nor npm - there's no need to run `npm install`, as all our deps are already included. `./tools/build_binding.js` is our alternative to that. I thought you meant `npm install propel` didn't work...
