### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Qti3e** [propelml/propel#277]
When entered number is grater than 2e7 it throws this wired error on Android (It works fine with my PC)
```
SyntaxError: Invalid number (2:0)
    at U.J.raise (http://propelml.org/website_main.js:1041:52486)
    at U.ot.readNumber (http://propelml.org/website_main.js:1041:65593)
    at U.ot.getTokenFromCode (http://propelml.org/website_main.js:1041:62915)
    at U.ot.readToken (http://propelml.org/website_main.js:1041:58058)
    at U.ot.nextToken (http://propelml.org/website_main.js:1041:57927)
    at U.ot.next (http://propelml.org/website_main.js:1041:57375)
    at U.j.eat (http://propelml.org/website_main.js:1041:10741)
    at U.j.expect (http://propelml.org/website_main.js:1041:11583)
    at U.G.parseBlock (http://propelml.org/website_main.js:1041:21087)
    at U.$.parseFunctionBody (http://propelml.org/website_main.js:1041:50029)
```

**Comment by Qti3e** [comment]
Additional information:
```
[in] 7e20
// Works as expected:
[out] 700000000000000000000
```

Random behaviours: 
```
[in] 7e16
[out] 70
```
```
[in] 7e16
[out] 70000000000000000
```

```
[in] 7e35
[out] 7000
```

```
[in] 7e21
[out] Reported 
```

this is completly random, even with same inputs I face diffrent situations

**Comment by piscisaureus** [comment]
@Qti3e were you able to figure out what causes this?

**Comment by Qti3e** [comment]
I guess it's because of slow layout rendering :thinking: 
When I hit the execute there are still some `setState`s to be done in preact and it would execute an incomplete version of the wanted code.
