### ISSUE TITLE
Hardcoded invalid dataset location in the npm dist

### ISSUE THREAD

**Issue by thefill** [propelml/propel#375]
It seems like your build script for dist package is messing with paths.

"propel@3.2.0" from npm contains lots of lines like this one:

`var __dirname = "/Users/rld/src/propel/src";`

Which causes errors when loading datasets.

**Comment by brandly** [comment]
can confirm.

```js
const { dataset } = require('propel')
dataset('mnist/train')
```
```
Using DL backend.
(node:27781) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/rld/src/propel/deps/data/mnist/train-images-idx3-ubyte'
    at Object.fs.openSync (fs.js:646:18)
    at fs.readFileSync (fs.js:551:33)
    at i (/home/paperspace/js/node_modules/propel/propel.js:107:1529)
    at Object.u [as fetchArrayBuffer] (/home/paperspace/js/node_modules/propel/propel.js:107:1648)
    at i (/home/paperspace/js/node_modules/propel/propel.js:143:583)
    at Object.s [as loadSplit] (/home/paperspace/js/node_modules/propel/propel.js:143:478)
    at mnist/train (/home/paperspace/js/node_modules/propel/propel.js:145:339)
    at o (/home/paperspace/js/node_modules/propel/propel.js:145:450)
    at Object.<anonymous> (/home/paperspace/js/dataset.js:2:1)
    at Module._compile (module.js:652:30)
```

**Comment by ry** [comment]
Yes this is a bug - thanks for the report. Will fix soon.

**Comment by ry** [comment]
@thefill @brandly It's taken a while, but we've finally cut a new release and it should work.
