### ISSUE TITLE
imshow should work with 2D images

### ISSUE THREAD

**Issue by ry** [propelml/propel#433]
```
import * as pr from "propel";
let ds = pr.dataset("mnist/test").batch(10);
let { images } = await ds.next();
pr.imshow(images.slice(0, 1).squeeze())

Error: Unsupported image rank.
    at Object.i [as toUint8Image] (http://propelml.org/sandbox.js:230:780)
    at Object.r [as imshow] (http://propelml.org/sandbox.js:232:717)
    at cell2 top level (cell2:4:4)
```

**Comment by qti3e** [comment]
oh... it's related to this:
https://github.com/propelml/propel/blob/62d9f57af332c4e9d52319e0e3d951c390582e94/src/im.ts#L52-L56

```ts
- if (shape.length === 3) { 
+ if (image.shape.length === 3) { 
```
