### ISSUE TITLE
imsave in npm module cannot find jpeg-js

### ISSUE THREAD

**Issue by dangerdak** [propelml/propel#454]
After installing using the npm module, using imsave causes the error: `Cannot find module 'jpeg-js'`
```
/.../node_modules/propel/propel.js:10560
        throw error;
        ^

Error: Cannot find module 'jpeg-js'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at newRequire (/.../node_modules/propel/propel.js:30:18)
    at newRequire (/.../node_modules/propel/propel.js:22:18)
    at Object.localRequire [as nodeRequire] (/.../node_modules/propel/propel.js:48:14)
    at jpegSaveHandler (.../node_modules/propel/propel.js:27846:25)
    at Object.imsave (/.../node_modules/propel/propel.js:27902:24)
    at run (/.../run-model.js:35:6)
```

**Comment by qti3e** [comment]
Hi, thanks for reporting this issue!
Can you confirm if you experience the same error with a png file?
you can try [this](http://propelml.org/src/testdata/sample.png) as a valid png file : )
